### ISSUE TITLE
Consider replacing usage of `GetDrakePath()` with environment variable

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/spartan#30]
Once the bazel-build of `drake` is used within `spartan`, any usages of `drake::GetDrakePath()` and `pydrake.getDrakePath()` will break, since it is stripped out via `bazel` (transitively, `package_drake.sh`) via this rule ([source](https://github.com/RobotLocomotion/drake/blob/3b9f6fc4ae4b6f1bd68dcaf72d21fbf71f893b24/drake/common/BUILD#L180)):

    name = "drake_path_genrule", ...
    cmd = "sed 's#@PROJECT_SOURCE_DIR@#drake#g' $< > $@",

I only see a few usages of `getDrakePath()` within Python code:

    $ grep -rnI --include={'*.py','*.cc','*.cpp','*.h'} --exclude-dir={build,drake} -i GetDrakePath
    apps/pr2/bhpnTranslator.py:103:    filename = os.path.join(pydrake.getDrakePath(), 'examples/PR2/pr2.urdf')
    director/src/python/director/drakevisualizer.py:192:            m.populateFromSearchPaths([pydrake.getDrakePath()])
    director/src/python/director/drcargs.py:92:        drakePath = pydrake.getDrakePath()
    director/src/python/director/treeviewer.py:303:            m.populateFromSearchPaths([pydrake.getDrakePath()])

These could be replaced by something such as `director.getDrakePath()`, which could leverage environment variables if need be.

\cc @manuelli @sammy-tri

**Comment by fbudin69500** [comment]
Since new functions to find resources have been added to drake, it would be nice to replace the `GetDrakePath()` calls with these new `find_resources` functions. However, there are no Python bindings for these functions yet (https://github.com/RobotLocomotion/drake/issues/6685)

**Comment by patmarion** [comment]
I think there are two uses of `pydrake.getDrakePath()` in director:

1) to crawl for package .xml files in order to resolve paths like `package://<name>/mesh.obj`.  This is done in `drakevisualizer.py` and `treeviewer.py`.

2) to get the path to the iiwa urdf file https://github.com/RobotLocomotion/director/blob/master/src/python/director/drcargs.py#L98

The feature provided by 2) allows users to pass `--iiwa-drake` on the command line to automatically import the iiwa config file.  I think most uses in spartan now load the config from `SPARTAN_SOURCE_DIR` and *not* drake.  So perhaps this whole feature can be removed or modified to use `SPARTAN_SOURCE_DIR`.

I think the feature provided by 1) needs to continue working, but the implementation could change if needed.

**Comment by peteflorence** [comment]
@EricCousineau-TRI can we close this issue now that we are in Drake bazel world?

**Comment by EricCousineau-TRI** [comment]
Done.
